name: smartgridapp
description: An application for the smart grid table.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  mqtt_client: ^9.8.0
  uuid: ^3.0.7
  provider: ^6.0.5
  image: ^4.0.15
  flutter_animated_icons: ^1.0.1
  invert_colors: ^0.0.4
  udp: ^5.0.3
  flutter_styled_toast: ^2.1.3
  flutter_settings_screens: ^0.3.3-null-safety+2
  shared_preferences: ^2.0.18
  asbool: ^1.0.6
  fl_chart: ^0.61.0
  auto_size_text: ^3.0.0
  intl: ^0.17.0

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  lints: ^2.0.1

dependency_overrides:
  intl: any

flutter:

  uses-material-design: true

  assets:
    - images/

